#----------------------------
# General settings
#----------------------------
data_dir: data
output_dir: output

base_year: 2020 
end_year: 2050 # final year for control totals output

targets_end_year: 2044 # year for which growth targets are set


#----------------------------
# Hard coded King County gq, hhsz and vacancy rates by rgid
# need to add these as calculations in the future once I find the source
#----------------------------
king_gq: # first column is rgid, second is gq percentage
  1: 3.4
  2: 1.2
  3: 1.6
  4: .3
  5: .3
  6: .4

king_hhsz: # first column is rgid, second is average household size
  1: 2.12
  2: 2.52
  3: 2.51
  4: 2.75
  5: 2.65
  6: 2.62

king_metro_adj_hhsz: 2.00 # adjusted hhsz used for king county metro rgid areas when calclulating hhpop
                          # for the targets, the rgid totals still use the king_hhsz value above

king_vac: # first column is rgid, second is vacancy rate percentage
  1: 4.7
  2: 4.4
  3: 3.6
  4: 3.0
  5: 3.0
  6: 5.0

king_hhpop_2044: 2828620 # target household population for king county in 2044
                         # not sure where this number comes from, will need to
                         # replace with calculated value in the future

#----------------------------
# Employment settings
#----------------------------
emp_target_types:
  includes res con: [53035, 53053] # Kitsap and Pierce targets include resource and construction employment
  excludes res con: [53033, 53061] # King, Snohomish targets do not include resource and construction employment

res_con_emp_growth_pct: 0.028 # percentage of employment growth from resource and construction
                              # ussed to adjust King and Snohomish employment growth targets since they 
                              # exclude resource and construction employment. Originally based on REF
                              # projections, will need to be updated, possibly with REMI

#----------------------------
# Census settings
#----------------------------
CensusKey: CENSUS_KEY # Environment variable name for Census API key

census_year: 2020
county_ids: [53033,53035,53053,53061]
state_id: 53

census_variables:
  dec_total_pop: # name variable will be changed to
    - P1_001N # variable code from census api
  dec_units:
    - H1_001N
  dec_hh:
    - H1_002N
  dec_gq:
    - P5_001N


#----------------------------
# Elmer settings
#----------------------------
# issues with pulling all columns from ElmerGeo, so columns need to be specified
ElmerGeo: # database
#  - name: control_areas # name the table will be saved as in h5
#    sql_table: CONTROL18_DASHBOARD # table in elmer
#    columns: # columns to pull from elmer
#     - control_id
#     - control_na
#     - county_id
#    id_col: control_id # id column must be an integer

#  - name: blocks
#    sql_table: BLOCK2020
#    columns:
#       - geoid20
#    id_col: geoid20 # id column must be an integer

#  - name: parcel_pts
#    sql_table: PARCELS_URBANSIM_2018_PTS
#    columns:
#       - parcel_id
#    id_col: parcel_id # id column must be an integer

 - name: regional_geographies
   sql_table: REGIONAL_GEOGRAPHIES
   columns: ['city_name','cnty_name','feat_type','juris','rgeo_class','class_desc']

 - name: county
   sql_table: COUNTY_BACKGROUND
   columns: 
    - county_fip
    - psrc

 - name: military_bases
   sql_table: MILITARY_BASES
   columns: ['milspn_id','name','psrc']

 - name: tribal_land
   sql_table: TRIBAL_LAND
   columns: ['tribal_land']

 - name: natural_resource
   sql_table: NAT_RESOURCE
   columns: ['resource']


# pull all columns for Elmer instead of specifying columns
Elmer: # database
#  - name: ofm_estimates_2020 # name the table will be saved as in h5
#    sql_table: ofm.v_estimates_2020 # table in elmer
#    id_col: block_geoid # id column must be an integer

#  - name: ofm_estimates_2019
#    sql_table: ofm.v_estimates_2019
#    id_col: block_geoid # id column must be an integer

#  - name: ofm_parcelized_2019
#    sql_table: ofm.parcelized_saep(2019, 2010)
#    id_col: parcel_id # id column must be an integer

#  - name: ofm_parcelized_2020
#    sql_table: ofm.parcelized_saep(2020, 2010)
#    id_col: parcel_id # id column must be an integer


#----------------------------
# tables to be read in from data folder
#----------------------------
data_tables:
 - name: control_target_xwalk
   file: control_target_xwalk.csv

 - name: ref_projection
   file: REF_projection.csv

 - name: employment_2019_by_control_area
   file: Employment 2019.csv
   no_mil_res_con_col: TotEmpNoMil-ResCon # column name for employment excluding military, resource and construction

 - name: employment_2020_by_control_area
   file: Employment 2020.csv
   no_mil_res_con_col: TotEmpNoMil-ResCon # column name for employment excluding military, resource and construction

targets_tables:
 - name: king_targets
   file: King Growth Targets 2021.csv
   units_chg_col: 2019-2044 Housing Target
   emp_chg_col: 2019-2044 Job Target
   units_chg_start: 2019
   emp_chg_start: 2019

 - name: kitsap_targets
   file: Kitsap Growth Targets 2021.csv
   total_pop_chg_col: 2020-2044 Population Growth
   emp_chg_col: 2020-2044 Employment Growth
   total_pop_chg_start: 2020
   emp_chg_start: 2020

 - name: pierce_targets
   file: Pierce Growth Targets 2021.csv
   total_pop_chg_col: 2020-2044 Population Growth
   emp_chg_col: 2020-2044 Employment Growth
   total_pop_chg_start: 2020
   emp_chg_start: 2020

 - name: snohomish_targets
   file: Snohomish Growth Targets 2021.csv
   total_pop_chg_col: Population Chg 2020-44
   emp_chg_col: Employment Chg 2019-44
   total_pop_chg_start: 2020
   emp_chg_start: 2019


#----------------------------
# shapefiles to be read in from data/shapefiles folder
#----------------------------
shapefiles:
#  - name: regional_geography
#    file: reggeog_22_allnames_edit.shp
#    id_col: RGid_22


#----------------------------
# Pypyr steps
#----------------------------
steps:
 - steps.get_elmer_data # pulls data from elmer database and saves to hdf5
 - steps.create_control_area_geography # creates control area geography by unioning and dissolving regional geographies, military bases, tribal areas, and natural resource areas together
#  - steps.get_census_data # pulls decennial census data from api and saves to hdf5
#  - steps.load_shapefiles # loads shapefiles in data/shapefiles into hdf5
#  - steps.load_data # loads data from csv files into hdf5
#  - steps.block_regional_geography_xwalk # creates block to regional geography crosswalk
#  - steps.parcel_control_area_xwalk # creates parcel to control area crosswalk
#  - steps.prepare_block_data # aggregates block data (ofm and decennial) to regional geography level
#  - steps.adjust_targets_to_base_year # adjusts targets to base year using ofm and employment data
#  - steps.units_chg_targets # calculates targets that use housing unit change (only king county for now)
#  - steps.total_pop_chg_targets # calculates targets that use total population change
#  - steps.emp_chg_targets_res_con # calculates targets for counties that include resource and construction employment
#  - steps.emp_chg_targets_no_res_con # calculates targets for counties that exclude resource and construction employment
#  - steps.emp_chg_targets_no_res_con # calculates targets for counties that exclude resource and construction employment
#  - steps.extrapolate_to_controls_year # extrapolates out to the control totals end year from the targets end year
